# Generated by Django 5.2 on 2025-06-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarxa', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/profiles/default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
